server {
    listen 80;
    server_name localhost;

    set $backend_url "http://backend:3000";
    set $frontend_url "http://frontend";

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        resolver 127.0.0.11 valid=10s;
        proxy_pass $backend_url;
        proxy_set_header Host $host;
        proxy_set_header Origin $frontend_url;
        proxy_set_header X-Real-IP $remote_addr;
        }

    location / {
        try_files $uri $uri/ /index.html;
        }   
    }
